/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SensorIndexRouteImport } from './routes/sensor/index'
import { Route as SensorSensorIdIndexRouteImport } from './routes/sensor/$sensorId.index'
import { Route as SensorSensorIdHistoryRouteImport } from './routes/sensor/$sensorId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorIndexRoute = SensorIndexRouteImport.update({
  id: '/sensor/',
  path: '/sensor/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorSensorIdIndexRoute = SensorSensorIdIndexRouteImport.update({
  id: '/sensor/$sensorId/',
  path: '/sensor/$sensorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorSensorIdHistoryRoute = SensorSensorIdHistoryRouteImport.update({
  id: '/sensor/$sensorId/history',
  path: '/sensor/$sensorId/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sensor': typeof SensorIndexRoute
  '/sensor/$sensorId/history': typeof SensorSensorIdHistoryRoute
  '/sensor/$sensorId': typeof SensorSensorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sensor': typeof SensorIndexRoute
  '/sensor/$sensorId/history': typeof SensorSensorIdHistoryRoute
  '/sensor/$sensorId': typeof SensorSensorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sensor/': typeof SensorIndexRoute
  '/sensor/$sensorId/history': typeof SensorSensorIdHistoryRoute
  '/sensor/$sensorId/': typeof SensorSensorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sensor' | '/sensor/$sensorId/history' | '/sensor/$sensorId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sensor' | '/sensor/$sensorId/history' | '/sensor/$sensorId'
  id:
    | '__root__'
    | '/'
    | '/sensor/'
    | '/sensor/$sensorId/history'
    | '/sensor/$sensorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SensorIndexRoute: typeof SensorIndexRoute
  SensorSensorIdHistoryRoute: typeof SensorSensorIdHistoryRoute
  SensorSensorIdIndexRoute: typeof SensorSensorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor/': {
      id: '/sensor/'
      path: '/sensor'
      fullPath: '/sensor'
      preLoaderRoute: typeof SensorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor/$sensorId/': {
      id: '/sensor/$sensorId/'
      path: '/sensor/$sensorId'
      fullPath: '/sensor/$sensorId'
      preLoaderRoute: typeof SensorSensorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor/$sensorId/history': {
      id: '/sensor/$sensorId/history'
      path: '/sensor/$sensorId/history'
      fullPath: '/sensor/$sensorId/history'
      preLoaderRoute: typeof SensorSensorIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SensorIndexRoute: SensorIndexRoute,
  SensorSensorIdHistoryRoute: SensorSensorIdHistoryRoute,
  SensorSensorIdIndexRoute: SensorSensorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
